project_id = "syunvnzadkbofewrjicz"

[functions.generate-code]
enabled = true
verify_jwt = false

[functions.create-build]
enabled = true
verify_jwt = false

[functions.generate-installer]
enabled = true
verify_jwt = false
